version: "2"

networks:
  audio_scraper:

services:
  frontend:
    build:
      context: client
      dockerfile: dev.Dockerfile
    ports:
      - 5000:5000
    environment:
      NODE_ENV: development
    volumes:
      - ./client:/client
    networks:
      - audio_scraper
    stdin_open: true
    tty: true