version: '3'

networks:
  audio_scraper:

services:
  frontend:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    ports:
      - 5000:5000
    environment:
      NODE_ENV: development
    volumes:
      - ./client:/client
      - /client/node_modules
    networks:
      - audio_scraper
    stdin_open: true
    tty: true